name: Swift

on:
  push:
    branches: [ develop-RxSwift ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    # Select Xcode version
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_12.2.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
      # Run build
    - name: Build
      run: xcodebuild
            -scheme Swift-github-actions
            -sdk iphonesimulator
            -configuration Debug
            build
      # Run unit test
    - name: Run tests
      run: xcodebuild
            -scheme Swift-github-actions
            -sdk iphonesimulator
            -destination 'platform=iOS Simulator,name=iPhone 11'
            clean test
