name: Swift

on:
  push:
    branches: [ develop-RxSwift ]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    # Select Xcode version
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
      # Run build
    - name: Build
      run: xcodebuild 
        -sdk iphonesimulator 
        -configuration Debug build 
      # Run unit test
    - name: Xcode test
      run: set -o pipefail &&
        xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -workspace {TodaysToDo}.xcworkspace
        -scheme {TodaysToDo}
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max'
        clean test
        | bundle exec xcpretty --report html
